# 2020-02-11(예외처리)

### 1.예외와 예외 클래스

- 에러란?
  - 하드웨어 오동작 또는 고장으로 인행 응용프로그램 실행 오류가 발생하는 것
  - 에러는 개발자가 관리할 수 없음
- 예외란?
  - 사용자의 잘못된 조작 또는 개발자의 잘못된 코딩으로 인해 발생하는 프로그럄 오류
  - 예외는 예외처리를 통해 프로그램을 종료시키지 않고 정상 실행 상태가 되도록 유지 
- 예외의 종류
  - 일반 예외
    - (=컴파일러 체크 예외) 자바 소스를 컴파일 하는 과정에서 예외 처리 코드가 필요한지 검사,
    - 일반 예외는 Exception의 상속을 받음
  - 실행 예외
    - 컴파일하는 과정에서 예외 처리 코드를 검사하지 않는 예외
    - 실행 예외는 RuntimeException의 상속을 받음

### 2. 실행 예외

- 자바 컴파일러가 체크를 하지 않기 때문에 오로지 개발자의 경험에 의해서 예외 처리 코드를 삽입 해야함
- 예외 처리 코드를 넣지 않으면 바로 프로그램이 종료됨

1. NullPointerException

   - 객체 참조가 없는 상태, 즉 null 값을 갖는 참조 변수로 객체 접근 연산자인 도트를 사용했을 때 발생

   - 예제

     ```java
     package chap10.p423;
     
     public class NullPointerExceptionExample {
     	public static void main(String[] args) {
     		String data = null;
     		System.out.println(data.toString()); //객체가 없는 상태
     	}
     }
     /*
     Exception in thread "main" java.lang.NullPointerException
     at chap10.p423.NullPointerExceptionExample.main(NullPointerExceptionExample.java:6)
     */
     ```

2. ArrayIndexnOutOfBoundsException

   - 배열에서 인덱스 범위를 초과하여 사용할 경우 발생

   - 예제

     ```java
     package chap10.p424;
     
     public class ArrayIndexOutOfBoundsException {
     	public static void main(String[] args) {
     		String data1 = args[0];
     		String data2 = args[1];
     		
             //실행 매개값을 주지 않았기 때문에 예외가 발생
     		System.out.println("args[0] = "+args[0]);
     		System.out.println("args[1] = "+args[1]);
     	}
     }
     /*
     Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
     at chap10.p423.ArrayIndexOutOfBoundsException.main(ArrayIndexOutOfBoundsException.java:5)
     */
     /*
     args[0] = 배열
     args[1] = 인덱스
     */
     ```

   - 배열값을 읽기 전에 배열의 길이를 조사해서 예외 발생을 막음

     ```java
     package chap10.p424;
     
     public class ArrayIndexOutOfBoundsException2 {
     	public static void main(String[] args) {
     		if(args.length == 2) {
     			String data1 = args[0];
     			String data2 = args[1];
     			System.out.println("args[0] : "+data1);
     			System.out.println("args[1] : "+data2);
     		}else {
     			System.out.println("[실행 방법]");
     			System.out.println("java ArrayIndexOutOfBoundsExceptionExample ");
     			System.out.println("값1    값2");
     		}
     	}
     }
     /*
     [실행 방법]
     java ArrayIndexOutOfBoundsExceptionExample 
     값1    값2
     */
     ```

3. NumberFormatException

   - Integer.parseInt(String s) / Double.pareseDouble(String s) 같은 메소드를 쓰면 문자열을 int타입이나 double타입으로 변환할 수 있는데 이때 숫자로 변환될 수 없는 문자가 포함되어 있다면 예외를 발생

   - 예제

     ```java
     package chap10.p426;
     
     public class NumberFormatException {
     	public static void main(String[] args) {
     		String data1 = "100";
     		String data2 = "a100";
     		
     		int value1 = Integer.parseInt(data1);
     		int value2 = Integer.parseInt(data2); //"a100"은 숫자로 변환 불가능
     		
     		int result = value1 + value2;
     		System.out.println(result);
     	}
     }
     /*
     Exception in thread "main" java.lang.NumberFormatException: For input string: "a100"
     at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
     at java.base/java.lang.Integer.parseInt(Integer.java:658)
     at java.base/java.lang.Integer.parseInt(Integer.java:776)
     at chap10.p426.NumberFormatException.main(NumberFormatException.java:9)
     */
     ```

4. ClassCastException

   - 억지로 타입 변환을 시도할 경우 발생

   - 예외를 발생을 막기위해 타입 변환 전에 미리 타입 변환이 가능하지 instanceof 연산자로 확인

   - 예제

     ```java
     package chap10.p428;
     
     public class ClassCastExceptionExample {
     	public static void main(String[] args) {
     		Dog dog = new Dog();
     		changeDog(dog); // Dog객체를 Dog타입으로 변환 가능하니?
     		
     		Cat cat = new Cat();
     		changeDog(cat); // Cat객체를 Dog타입으로 변환가능하니
     		
     	}
     	
     	public static void changeDog(Animal animal) {
     	//	if(animal instanceof Dog) {
     			Dog dog =(Dog)animal;
     	//	}
     	}
     }
     class  Animal{}
     class Dog extends Animal{}
     class Cat extends Animal{}
     
     /*
     Exception in thread "main" java.lang.ClassCastException: class chap10.p428.Cat cannot be cast to class chap10.p428.Dog (chap10.p428.Cat and chap10.p428.Dog are in unnamed module of loader 'app')
     at chap10.p428.ClassCastExceptionExample.changeDog(ClassCastExceptionExample.java:15)
     at chap10.p428.ClassCastExceptionExample.main(ClassCastExceptionExample.java:9)
     */
     ```

### 3. 예외 처리 코드

- 일반 예외가 발생할 가능성이 있는 코드를 발견하면 컴파일 오류를 발생시켜 개발자로 하여금 강제적으로 예외 처리 코드를 작성하도록 요구

- 실행 예외는 컴파일러가 체크해주지 않기 때문에 예외 처리 코드를 개발자의 경험을 바탕으로 작성해야 한다 try-catch-finally 블록을 이용

  ```java
  try{
      //예외 발생 가능 코드
  }catch(예외클래스 e){
      //예외처리 ,예외가 발생하지 않으면 넘어감
  }finally{
      //항상 실행
  }
  ```

- 예제

  ```java
  package chap10.p431;
  
  public class TryCatchFinallyExample {
  	public static void main(String[] args) {
  		try {
  		//Class.forName() 매개값으로 주어진 클래스가 있으면 Class객체 리턴,없으면 예외
  			Class clazz = Class.forName("java.lang.String2"); // java.lang.String2 클래스가 있으면 Class 객체를 리턴, 아니면 예외를 발생
  		} catch (ClassNotFoundException e) {
  			System.out.println("클래스가 존재하지 않습니다.");
  		}
  	}
  }
  /*
  클래스가 존재하지 않습니다.
  */
  ```

- 예제

  ```java
  package chap10.p431;
  
  public class TryCatchFinallyRuntimeExceptionExample {
  	public static void main(String[] args) {
  		String data1 = null;
  		String data2 = null;
  		try {
  			data1 = args[0];
  			data2 = args[1];
  		} catch (ArrayIndexOutOfBoundsException e) {
  			System.out.println("실행 매개값의 수가 부족합니다.");
  			System.out.println("[실행 방법]");
  			System.out.println("java ArrayIndexOutOfBoundsException num1 num2");
  			return;
  		}
  		
  		try {
  			int value1 = Integer.parseInt(data1);
  			int value2 = Integer.parseInt(data2);
  			int result = value1 + value2;
  			System.out.println(result);
  		} catch (NumberFormatException e) {
  			System.out.println("숫자로 변환할 수 없습니다.");
  		}finally {
  			System.out.println("다시 실행하세요");
  		}
  		System.out.println("계속 진행됩니다.");
  	}
  }
  /*
  실행 매개값의 수가 부족합니다.
  [실행 방법]
  java ArrayIndexOutOfBoundsException num1 num2
  */
  
  /*
  숫자로 변환할 수 없습니다.
  다시 실행하세요
  계속 진행됩니다.
  */
  ```

### 4. 예외 종류에 따른 처리 코드

1. 다중 catch

   - try 블록 내부는 다양한 종류의 예외가 발생 -> 다중 catch블록을 작성

   - try블록에서 해당 타입의 예외가 발생하면 catch 블록을 실행

   - catch블록이 여러 개라도 단 하나의 catch블록만 실행한다.

   - 예제

     ```java
     package chap10.p434;
     
     public class CatchByExceptionKindExample {
     	public static void main(String[] args) {
     		try {
     			String data1 = args[0];
     			String data2 = args[1];
     			int value1 = Integer.parseInt(data1);
     			int value2 = Integer.parseInt(data2);
     			int result = value1 + value2;
     			System.out.println(result);
     		} catch (ArrayIndexOutOfBoundsException e) {
     			System.out.println("실행 매개값의 수가 부족하니다.");
     		} catch (NumberFormatException e) {
     			System.out.println("숫자로 변환할 수 없습니다.");
     		} finally {
     			System.out.println("다시 실행하세요.");
     		}
     	}
     }
     /*
     실행 매개값의 수가 부족하니다.
     다시 실행하세요.
     */
     
     ```

2.  catch 순서

   - 다중 catch 블록을 작성할 때 상위 예외 클래스가 하위 예외 클래스보다 아래쪽에 위치 해야한다.

   - 안그러면 상위 클래스에서 모든 예외를 처리

   - 예제

     ```java
     package chap10.p436;
     
     public class CatchOrderExample {
     	public static void main(String[] args) {
     		try {
     			String data1 = args[0];
     			String data2 = args[1];
     			int value1 = Integer.parseInt(data1);
     			int value2 = Integer.parseInt(data2);
     			int result = value1 + value2;
     			System.out.println(result);
     		}catch (ArrayIndexOutOfBoundsException e) { //catch블록에서 하위 클래스가 상위 클래스 위에 있어야한다.
     			System.out.println("실행 매개값의 수가 부족합니다.");
     		}catch (Exception e) {
     			System.out.println("실행에 문제가 있습니다.");
     		}finally {
     			System.out.println("다시 실행하세요");
     		}
     	}
     }
     /*
     실행 매개값의 수가 부족합니다.
     다시 실행하세요
     */
     ```

3. 멀티 catch

   - 하나의 catch 블록에서 여러 개의 예외를 처리할 수 있도록 멀티 catch 기능을 추가

   - 예제

     ```java
     package chap10.p437;
     
     public class MultiCatchExample {
     	public static void main(String[] args) {
     		try {
     			String data1 = args[0];
     			String data2 = args[1];
     			int value1 = Integer.parseInt(data1);
     			int value2 = Integer.parseInt(data2);
     			int result = value1 + value2;
     			System.out.println(result);
     		}catch (ArrayIndexOutOfBoundsException | NumberFormatException e) { //catch블록에서 하위 클래스가 상위 클래스 위에 있어야한다.
     			System.out.println("실행 매개값의 수가 부족하거나, 숫자로 변환할 수 없습니다.");
     		}catch (Exception e) {
     			System.out.println("알수없는 예외발생.");
     		}finally {
     			System.out.println("다시 실행하세요");
     		}
     	}
     }
     /*
     실행 매개값의 수가 부족하거나, 숫자로 변환할 수 없습니다.
     다시 실행하세요
     */
     
     ```

### 5. 자동 리소스 담기

- 리소스란 

  - 데이터를 읽고 쓰는 객체

- try-with-resources를 사용하면 예외 발생 여부와 상관없이 사용했던 리소스 객체의 close() 메소드를 호출해서 안전하게 리소스를 닫아줌

- 자바 6 이전에는 close() 메소드를 명시적으로 호출해줘야 하지만 자바 7 이후부터는 try블록이 정상적으로 실행을 완료했거나 도중에 예외가 발생하면 close()메소드를 자동으로 호출하게 된다.

- try-with-resources를 사용하기 위해서 리소스 객체는 AutoCloseable  인터페이스를 구현해야지 close()메소드가 자동 호출된다.

- 예제

  ```java
  package chap10.p439;
  
  public class FileInputStream implements AutoCloseable {
  	@Override
  	public void close() throws Exception { //try블록을 정상적으로 실행하거나 예외 발생시 자동 호출
  		System.out.println(file +"을 닫습니다.");
  	}
  	
  	private String file;
  	
  	public FileInputStream(String file) {
  		this.file= file;
  	}
  	
  	public void read() {
  		System.out.println(file + "을 읽습니다.");
  	}
  	
  
  }
  
  ```

  ```java
  package chap10.p439;
  
  public class TryWithResourceExample {
  	public static void main(String[] args) {
  		try(FileInputStream fis = new FileInputStream("file.txt")){
  			fis.read();
  			throw new Exception(); //강제적으로 예외 발생시킴
  		} catch (Exception e) {
  			System.out.println("예외 처리 코드가 실행 되었습니다.");
  		}
  	}
  }
  /*
  file.txt을 읽습니다.
  file.txt을 닫습니다.
  예외 처리 코드가 실행 되었습니다.
  */
  
  ```

### 6. 예외 떠넘기기

- try-catch로 예외를 처리하는 것이 기본이지만 경우에 따라서 메소드를 호출할 곳으로 예외를 떠넘길 수도 있다.

- throws키워드는 메소드 선언부 끝에 작성되어 메소드에서 처리하지 않은 예외를 호출한 곳으로 떠넘기는 역활

  ```java
  리턴타입 메소드명(매개변수,..) throws 예외클래스1,예외클래스2,...{
      
  }
  
  리턴타입 메소드명(매개변수,..) throws Exception{
      //모든 예외를 떠넘김
  }
  ```

- throws 키워드가 붙어있는 메소드는 반드시 try 블록 내에서 호출 

- 자바 API 도큐먼트에 보면 클래스 생성자와 메서드 선언부에 throws 키워드가 붙어 있는 것들이 있는데  이러한 생성자와 메소드를 사용하고 싶다면 반드시 try-catch 블록으로 예외 처리 해야한다.

- main() 메소드 에서도 throws 키워드를 사용하면 JVM이 최종적으로 예외를 처리하는데, JVM은 예외의 내용을 콘솔에 출력

- 예제

  ```java
  package chap10.p442;
  
  public class ThrowsExample {
  	public static void main(String[] args) {
  		try {
  			findClass();
  		} catch (ClassNotFoundException e) {
  			System.out.println("클래스가 존재하지 않습니다.");
  		}
  	}
  	public static void findClass() throws ClassNotFoundException {
  		Class clazz = Class.forName("java.lang.String2");
  	}
  }
  /*
  클래스가 존재하지 않습니다.
  */
  
  ```


### 7. 사용자 정의 예외와 예외 발생

- 자바 표준 API 에 존재하지는 않지만 개발자가 필요한 예외는 직접 만들어서 사용할 수 있다.



1. 사용자 정의 예외 클래스 선언

   - 사용자 정의 예외도 Exception을 상속하는 일반 예외, RuntimeException을 상속하는 실행 예외로 만들 수 있다.

   - 정의

     ```java
     public class XXException extends [Exception | RuntimeException]{
     	public XXException{}
     	public XXException(String message){
     		super(message);
     	}
     }
     ```

     - 자용자 정의 예외 클래스의 이름은 Exception으로 끝나는 것이 좋다
     - 대부분 생성자만 선언
     - 생성자는 기본생성자와 예외 메세지를 전달할 수 있는 String 타입을 매개변수로 받는 생성자를 선언

   - 예제

     ```java
     package chap10.p444;
     
     public class BalanceInsufficientException extends Exception{ // 사용자 정의 예외 클래스
     	public BalanceInsufficientException() {
     	}
     	public BalanceInsufficientException(String message) {
     		super(message); //상위클래스의 생성자에 메세지를 넘겨줌
     	}
     }
     
     ```

2. 예외 발생시키기

   - 예외 발생 방법

     ```java
     thorw new XXException();
     thorw new XXException(String message);
     ```

   - 예제

     ```java
     package chap10.p444;
     
     public class Account {
     	private long balance;
     
     	public long getBalance() {
     		return balance;
     	}
     	public void deposit(int money) {
     		balance += money;
     	}
     	public void withdraw(int money) throws BalanceInsufficientException{ // withdraw를 호출한 곳에서 예외를 처리
     		if(balance < money) { //사용자 정의 예외 발생
     			throw new BalanceInsufficientException("잔고부족: "+(money-balance)+"모자람");
     		}
     		balance -= money;
     	}
     	
     }
     
     ```

3. 예외 정보 얻기

   - catch 블록에서 예외의 정보를 얻을 수 있다.

   - 예외의 정보를 얻을때는 catch블록의 매개값으로 전달된 예외 객체의 getMessage() , printStackTrace() 메소드를 사용한다.

   - getMessage() : String타입의 메세지를 갖는 생성자를 이용했다면 메세지를 리턴값으로 제공

   - printStackTrace() : 예외 발생 코드를 추적해서 모두 콘솔에 출력

   - 예제

     ```java
     package chap10.p444;
     
     public class AccountExample {
     	public static void main(String[] args) {
     		Account account = new Account();
     		
     		account.deposit(10000);
     		System.out.println("예금액 : "+account.getBalance());
     		
     		try {
     			account.withdraw(30000);
     		} catch (BalanceInsufficientException e) {
     			String message = e.getMessage(); //생성자에 저장된 String값을 리턴함
     			System.out.println(message); 
     			System.out.println();
     			e.printStackTrace(); //예외 발생 코드를 추첮ㄱ해서 모두 콘솔에 출력
     		}
     	}
     }
     /*
     예금액 : 10000
     잔고부족: 20000모자람
     
     chap10.p444.BalanceInsufficientException: 잔고부족: 20000모자람
     	at chap10.p444.Account.withdraw(Account.java:14)
     	at chap10.p444.AccountExample.main(AccountExample.java:11)
     */
     ```

     

